Daily work autocommit
git-svn-id: http://project.knowledgeforge.net/ukparse/svn/trunk@2273 9cc54934-f9f6-0310-8a8d-e8e977684441

diff --git a/parlparse/scripts/morningupdate b/parlparse/scripts/morningupdate
--- a/parlparse/scripts/morningupdate
+++ b/parlparse/scripts/morningupdate
@@ -19,9 +19,13 @@ source ~/parlparse/scripts/consts
 # Run scraper
 cd ~/parlparse/scripts
 ./updatedaterange-scrape $DAILY_FROMDATE $DAILY_TODATE $1
+echo "FAI aggregate error is $?"
 ./updatedaterange-parse $DAILY_FROMDATE $DAILY_TODATE $1
+echo "FAI aggregate error is $?"
 ./lordsupdatedaterange-scrape $DAILY_FROMDATE $DAILY_TODATE $1
+echo "FAI aggregate error is $?"
 ./lordsupdatedaterange-parse $DAILY_FROMDATE $DAILY_TODATE $1
+echo "FAI aggregate error is $?"
 
 ./other-sites-update
 
diff --git a/parlparse/scripts/quickupdate b/parlparse/scripts/quickupdate
--- a/parlparse/scripts/quickupdate
+++ b/parlparse/scripts/quickupdate
@@ -10,12 +10,16 @@ source ~/parlparse/scripts/consts
 cd ~/parlparse/scripts
 echo "Scraping commons"
 ./updatedaterange-scrape $NOW_FROMDATE $NOW_TODATE
+echo "FAI aggregate error is $?"
 echo "Parsing commons"
 ./updatedaterange-parse $NOW_FROMDATE $NOW_TODATE --patchtool
+echo "FAI aggregate error is $?"
 echo "Scraping lords"
 ./lordsupdatedaterange-scrape $NOW_FROMDATE $NOW_TODATE
+echo "FAI aggregate error is $?"
 echo "Parsing lords"
 ./lordsupdatedaterange-parse $NOW_FROMDATE $NOW_TODATE --patchtool
+echo "FAI aggregate error is $?"
 
 echo "Calling update of other sites"
 ./other-sites-update
