Add Norwegian O-slash. Add Justice ministry. Error handling (display only for now)
git-svn-id: http://project.knowledgeforge.net/ukparse/svn/trunk@2266 9cc54934-f9f6-0310-8a8d-e8e977684441

diff --git a/parlparse/scripts/updatedaterange-parse b/parlparse/scripts/updatedaterange-parse
--- a/parlparse/scripts/updatedaterange-parse
+++ b/parlparse/scripts/updatedaterange-parse
@@ -12,9 +12,13 @@ TODATE=$2
 cd ~/parlparse/pyscraper
 # We do these on separate lines, so if one fails, others still run
 ./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse debates
+echo "FAI test error is $?"
 ./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse wrans
+echo "FAI test error is $?"
 ./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse westminhall
+echo "FAI test error is $?"
 ./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse wms
+echo "FAI test error is $?"
 
 # Yeah, it's not as fully featured as the UK Parliament one. But it should work :)
 cd ~/parlparse/pyscraper/ni
